/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeProfileRouteImport } from './routes/me/profile'
import { Route as MeDocumentsRouteImport } from './routes/me/documents'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiDocumentsUploadRouteImport } from './routes/api/documents/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MeRoute,
} as any)
const MeDocumentsRoute = MeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MeRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ApiDocumentsUploadRoute = ApiDocumentsUploadRouteImport.update({
  id: '/api/documents/upload',
  path: '/api/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/me/documents': typeof MeDocumentsRoute
  '/me/profile': typeof MeProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/me/documents': typeof MeDocumentsRoute
  '/me/profile': typeof MeProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/me/documents': typeof MeDocumentsRoute
  '/me/profile': typeof MeProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/me'
    | '/auth/login'
    | '/auth/register'
    | '/me/documents'
    | '/me/profile'
    | '/api/auth/$'
    | '/api/documents/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me'
    | '/auth/login'
    | '/auth/register'
    | '/me/documents'
    | '/me/profile'
    | '/api/auth/$'
    | '/api/documents/upload'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/me'
    | '/auth/login'
    | '/auth/register'
    | '/me/documents'
    | '/me/profile'
    | '/api/auth/$'
    | '/api/documents/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MeRoute: typeof MeRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsUploadRoute: typeof ApiDocumentsUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/documents': {
      id: '/me/documents'
      path: '/documents'
      fullPath: '/me/documents'
      preLoaderRoute: typeof MeDocumentsRouteImport
      parentRoute: typeof MeRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/documents/upload': {
      id: '/api/documents/upload'
      path: '/api/documents/upload'
      fullPath: '/api/documents/upload'
      preLoaderRoute: typeof ApiDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MeRouteChildren {
  MeDocumentsRoute: typeof MeDocumentsRoute
  MeProfileRoute: typeof MeProfileRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeDocumentsRoute: MeDocumentsRoute,
  MeProfileRoute: MeProfileRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MeRoute: MeRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsUploadRoute: ApiDocumentsUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
